/*
DUDAS:

GENERAR UNA LISTA CON DATOS DEL PACIENTE Y DEL CONTACTO DE LOS RECUPERABLES PARA PASARLE A LA SECRETARIA

STRING:
REGEX PARA SEPARAR Y DESPUES STOI PARA CONVERTIRLO A INT --> DE INT A TIME_T

*/